### ISSUE TITLE
training iteration doesn't actually update the grid base point positions

### ISSUE THREAD

**Issue by iszihan** [fidler-lab/defgrid-release#7]
Hello, I set up the gridpool.py to train. While looking into the codes, it seems every forward iteration of DGNet doesn't actually update the initial grid base point positions, i.e. the predicted offset is always with respect to the initial base point positions, which is a little confusing to me. I'm wondering if this is a bug or if you could point me to the part that updates the grid positions every iteration? Thank you in advance!

**Comment by SteveJunGao** [comment]
Yes, this part is intentional. As mentioned in the paper, we deform from a uniform grid, which is the initial base point positions here and is kept fixed, the position of the deformed grid is the predicted offset plus the initial base point position (this line of code https://github.com/fidler-lab/defgrid-release/blob/pooling/Models/GNN/superpixel_grid.py#L84). At every iteration, we predict different offsets for different images, so the deformed grid positions will be different accordingly.  The gradients are also backward through these offsets.

**Comment by iszihan** [comment]
I see. Thank you for the answers!
